"""Initial migration with Product model

Revision ID: f5eabd24c58f
Revises: 
Create Date: 2025-11-26 15:06:26.045639+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5eabd24c58f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index('ix_products_active_created', 'products', ['active', sa.text('created_at DESC')], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index('uq_products_sku_lower', 'products', [sa.text('lower(sku)')], unique=True, postgresql_ops={'sku': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_products_sku_lower', table_name='products', postgresql_ops={'sku': 'text_pattern_ops'})
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index('ix_products_active_created', table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###

